"""TSMMig1

Revision ID: 6aed626aedcd
Revises: d964d136b64f
Create Date: 2024-12-18 11:56:22.670701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aed626aedcd'
down_revision: Union[str, None] = 'd964d136b64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Name', sa.String(length=32), nullable=False),
    sa.Column('Description', sa.String(length=256), nullable=True),
    sa.Column('Permissions', sa.String(length=256), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Users',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('UserName', sa.String(length=32), nullable=False),
    sa.Column('Email', sa.String(length=64), nullable=False),
    sa.Column('HashedPassword', sa.String(length=256), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('UserName')
    )
    op.create_table('UsersRoles',
    sa.Column('UserId', sa.String(length=36), nullable=False),
    sa.Column('RoleId', sa.String(length=36), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['RoleId'], ['Roles.Id'], ),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], ),
    sa.PrimaryKeyConstraint('UserId', 'RoleId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UsersRoles')
    op.drop_table('Users')
    op.drop_table('Roles')
    # ### end Alembic commands ###
