"""TSMMig2

Revision ID: c57197c57056
Revises: 6aed626aedcd
Create Date: 2024-12-18 12:17:19.285007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57197c57056'
down_revision: Union[str, None] = '6aed626aedcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Roles', 'Permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Roles', sa.Column('Permissions', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
